[package]
name = "keepass-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
anyhow = "1.0.63"
async-fs = "1.6.0"
futures = "0.3.24"
reqwest = "0.11.11"
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.21.0", features = ["full"] }
